### ISSUE TITLE
SS3 sequence

### ISSUE THREAD

**Issue by gwenn** [alacritty/vte#101]
On MacOS, F1 key is reported as `ESC-O-P` (`[27, 79, 80]`) sequence.
But `vte` reports two events:
```sh
vte % cargo run --example parselog
^[OP
[esc_dispatch] intermediates=[], ignore=false, byte=4f
[print] 'P'
```
Could `vte` be extended to report a single event ?
Thanks.

https://en.wikipedia.org/wiki/C0_and_C1_control_codes#C1_control_codes_for_general_use
> Next character invokes a graphic character from the G2 or G3 graphic sets respectively.

**Comment by chrisduerr** [comment]
C1s are a bad idea and intentionally not supported.
