### ISSUE TITLE
Read user input

### ISSUE THREAD

**Issue by gwenn** [alacritty/vte#108]
Would it be possible to use `vte` to read user input (keyboard / mouse) in raw mode ?
I am doing experiments [here](https://github.com/gwenn/vte/tree/hack).
And it appears that some key sequences are not reported like:
- Shift-Tab
- Alt-Enter
- Alt-Backspace

Thanks.

**Comment by kchibisov** [comment]
It's for generally parsing escapes you get from the application and implement virtual terminal emulator, not for the application side itself, since it's _different_. It could be improved to handle both sides of the equation, but there're already creates doing so, like crossterm.

**Comment by gwenn** [comment]
But `crossterm` is [huge](https://github.com/crossterm-rs/crossterm/blob/08762b3ef4519e7f834453bf91e3fe36f4c63fe7/Cargo.toml#L35).
And [termwiz](https://github.com/wez/wezterm/blob/f07cc837166dc5f29df56afb42af3d6887ec6a33/termwiz/src/escape/parser/mod.rs#L11) is partially using [vtparse](https://crates.io/crates/vtparse/reverse_dependencies) for interpreting user input (`vtparse` ~= `vte`) but has the same issue.

I would like to replace this [mess](https://github.com/kkawakam/rustyline/blob/77f1d53fd8825d56c56b5528eac21fbdb6995a2d/src/tty/unix.rs#L201-L682) (which has been around longer than `crossterm`) without depending on async io.

**Comment by kchibisov** [comment]
This is pretty much out-of-scope for this library, however nothing stops from building derivative for client part of terminal apps.

I don't want to have a decoding of kitty/terminfo/all other stuff here.

Like input is more complicated than you might think of it.

**Comment by chrisduerr** [comment]
> It's for generally parsing escapes you get from the application and implement virtual terminal emulator, not for the application side itself, since it's different. It could be improved to handle both sides of the equation, but there're already creates doing so, like crossterm.

This is not entirely true. Most existing libraries like crossterm are pretty bad and VTE is perfectly capable of handling the client side of things too: https://github.com/chrisduerr/sketch/blob/master/Cargo.toml#L8

**Comment by gwenn** [comment]
@chrisduerr So should I reopen this issue ?

**Comment by kchibisov** [comment]
No, it's already possible.  If you want something like `ansi` but for client, that part is out of scope.
