### ISSUE TITLE
Publish a new version of vte_generate_state_changes to include license files

### ISSUE THREAD

**Issue by erickt** [alacritty/vte#113]
Hello all! Back in https://github.com/alacritty/vte/pull/111 symlinks got made to include the license files in the crate, but the latest released version 0.1.1 doesn't include them, which can be seen on https://docs.rs/crate/vte_generate_state_changes/latest/source/. Maybe an old version of cargo was used to make the package that didn't include them? I checked locally and using the latest version works:

```
% cd vte_generate_state_changes
% cargo package
...
% ls ../target/package/vte_generate_state_changes-0.1.1
Cargo.toml  Cargo.toml.orig  LICENSE-APACHE  LICENSE-MIT  src  target
```

So maybe all that needs to happen is to bump the version and regenerate the package?

**Comment by chrisduerr** [comment]
Shouldn't be much of an issue. Just out of curiosity, do you actually need this for something? The license is provided in the manifest, so I don't think this should cause much of an issue generally?

**Comment by chrisduerr** [comment]
Note that this issue likely also applies to `utf8parse`.

**Comment by erickt** [comment]
Yeah, it's a requirement from my company, that way there's no ambiguity about what is the text of the license that covers some piece of code.

**Comment by chrisduerr** [comment]
I've released the new versions.
