### ISSUE TITLE
Unexpected binaries in the published crate

### ISSUE THREAD

**Issue by FauxFaux** [alacritty/vte#27]
A concerned citizen, although apparently not concerned enough to use github, has noticed something that concerns them.
Some binaries, named `vim10m_match` and `vim10m_table`, have made it into the `vte 0.3.3` release on crates.io, visible https://docs.rs/crate/vte/0.3.3/source/

These binaries then get `vendor`'d into the actual `rustc` source downloads.

Could you please do a release which.. doesn't have random binaries, and other unpublished code, in?

**Comment by jwilm** [comment]
Browsing the link you provided, there's a vim10m.rs file that looks familiar. I need to check my other machine, but I believe that's code related to some experimenting I did a long time ago. I guess cargo must bundle whatever is in the working directory? Or at least did at the time..

I'll report back on that. We can certainly publish a clean version in any case.

**Comment by FauxFaux** [comment]
I believe `cargo publish` (nowadays) tries hard to not publish uncommitted stuff, but maybe you were on a branch, or something. All good!

**Comment by kchibisov** [comment]
@chrisduerr I feel like this should be closed now, since we've released v0.4.0 and v0.5.0 already.
