### ISSUE TITLE
DCS parameters not reset at unhook

### ISSUE THREAD

**Issue by dnkl** [alacritty/vte#46]
alacritty 0.4.1

It seems parameter(s) are not reset at the end of an DCS. Some examples:

"hello" should be colored red, but isn't:
```sh
echo -e '\eP1X\e\\\e[31mhello\e[m'
```
"hello" should **not** be colored, but is:
```sh
echo -e '\eP31X\e\\\e[mhello\e[m'
```
"hello" should **not** be bold, but is:
```sh
echo -e '\eP1X\e\\\e[mhello\e[m'
```

All the above works in xterm and urxvt.

For a real-world example, see https://codeberg.org/dnkl/page, it uses the (not yet standardized) [BSU/ESU](https://gitlab.freedesktop.org/terminal-wg/specifications/merge_requests/2) DCS sequences and it is completely broken in Alacritty (do `cat <large-file> | page` and scroll).

**Comment by chrisduerr** [comment]
Fixed in https://github.com/alacritty/vte/pull/47.

**Comment by dnkl** [comment]
Thanks!
