### ISSUE TITLE
Provide enum interface for next parser action

### ISSUE THREAD

**Issue by Timidger** [alacritty/vte#62]
The trait interface limits the error handling considerably when doing any advanced work in the callbacks. E.g. when doing file I/O the errors cannot be easily returned without employing temporary state.

Exposing an enum of the states (that would match the input parameters to the trait's functions) that can be accessed via a similar function to `advance` would allow this alternative use case.

This does increase the API surface area. However, the implementation can be reworked so that internally it uses the enum and only at the API surface is it decided whether to return that value directly vs calling the appropriate function.

**Comment by chrisduerr** [comment]
You say that the goal would be to fix error handling without employing temporary state, but it just sounds like you're interested in employing temporary state in vte?

Wouldn't it make more sense to have that state only in the consumer, rather than forcing it on everyone even if they are not interested in handling it?

What kind of error handling are you interested in that would require propagation outside of the callbacks? It seems like usually the outside effect of things should be relatively limited to the parser anyways.

> However, the implementation can be reworked so that internally it uses the enum and only at the API surface is it decided whether to return that value directly vs calling the appropriate function.

I'm not exactly sure what you mean by this. Do you want to add an extra step that checks if a function should be dispatched? That seems like it would be detrimental for performance.

**Comment by Timidger** [comment]
I started work on this but found that due to how its structured it would require significant rework. I employed a wrapper trait in my personal project that adds a `Result`. A kludge, but an okish one for now.

Here's what I was envisioning instead:

```

/// Actions to take based on the input and the current parser state.
pub enum ParserAction<'parser> {
    Print(char),
    Execute { byte: u8 },
    Hook { params: &'parser [i64], intermediates: &'parser [u8], ignore: bool, action: char },
    Put { byte: u8 },
    Unhook,
    OscDispatch { params: &'parser [&'parser [u8]], bell_terminated: bool },
    CsiDispatch { params: &'parser [i64], intermediates: &'parser [u8], ignore: bool, action: char },
    EscDispatch { intermediates: &'parser [u8], ignore: bool, byte: u8 },
}

impl Parser {
    pub fn advance<P: Perform>(&mut self, performer: &mut P, byte: u8) {
        match get_next_state() {
            None => {},
            // TODO Match on ParserAction enum
        }
    }

    /// Advance the parser state and return an enum describing the triggered event.
    pub fn next_state(&mut self, byte: u8) -> Option<ParserAction> {
        self.get_next_state(byte)
    }

    fn get_next_state(&mut self, byte: u8) -> Option<ParserAction> {
        // Do parse logic here
    }
}
```

If the extra conditional on the match is really a performance issue that is not dwarfed by the dynamic dispatch being done (I don't have measurements, I assume you do) then it probably would be overly prohibitive to have two separate code paths.

**Comment by chrisduerr** [comment]
I feel like this would actually make the API significantly worse and harder to use. Having to separately advance and get the state, then interpret it correctly would mean that users have to do more and the performance is probably worse.

I'm not sure what exact error handling requirements you have, but I feel like building those on top of the existing API would be a lot cleaner than the alternative you've suggested.

So unless there's a concrete API suggestion that would make things easier to use without sacrificing performance, I'm inclined to just instruct people to handle errors with some separate state.
